server:
   port:   8092
   servlet:
      name: /${spring.application.name}
   http:
      encoding:
         charset: utf-8
         force: true
         enabled: true
spring:
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/taoism?characterEncoding=utf8&useSSL=false
      username: root
      password: c$2N$Gdp
      driver-class-name: com.mysql.jdbc.Driver
mybatis:
   config-location: classpath:mybatis/mybatis.xml
   mapperLocations: classpath:mybatis/mapper/*.xml