server:
   port: 8092
   servlet:
      name: /${spring.application.name}
   http:
      encoding:
         charset: utf-8
         force: true
         enabled: true
spring:
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/taoism?characterEncoding=utf8&useSSL=false
      username: root
      password: c$2N$Gdp
      driver-class-name: com.mysql.jdbc.Driver
   redis:
      database: 0
      host: 101.133.218.111
      port: 6379
      jedis:
         pool:
            #最大连接数
            max-active: 8
            #最大阻塞等待时间(负数表示没限制)
            max-wait: -1
            #最大空闲
            max-idle: 8
            #最小空闲
            min-idle: 0
      #连接超时时间
      timeout: 10000
mybatis:
   config-location: classpath:mybatis/mybatis.xml
   mapperLocations: classpath:mybatis/mapper/*.xml